# Generated by Django 5.1.5 on 2025-02-16 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0004_projectgroup_members'),
        ('posts', '0003_alter_post_group'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectGroup',
        ),
    ]
